hypercerts-org/hypercerts-indexer

src/indexer/indexClaimsStored.ts
src/storage/storeHypercerts.ts
src/utils/getDeployment.ts
supabase/seed.sql

* Input claimIDs as strings in supabase-js because bigint got parsed as number resulting in 340282366920938460000000000000000000000 instead of 340282366920938463463374607431768211456

fix(store): bigint input as string to prevent 000..000 masking

---

src/indexer/indexAttestations.ts
src/parsing/attestationData.ts
src/server.ts
src/utils/parseSchemaToAbi.ts

* Parse schema from contract to ABI for decoding fields typed and with names
* Update indexer to update lastBlockIndexed when no attestations are found

feat(parse): cleaner schema parsing and error handling

---

package.json
pnpm-lock.yaml
src/indexer/indexAllowlistData.ts
src/indexer/indexAllowlistRecords.ts
src/indexer/indexAttestations.ts
src/indexer/indexClaimsStored.ts
src/indexer/indexFractionTransfers.ts
src/indexer/indexMetadata.ts
src/indexer/indexSupportedSchemas.ts
src/indexer/indexUnitTransfers.ts
src/indexer/runIndexing.ts
src/server.ts
src/storage/getContractEventsForChain.ts
src/storage/getMissingAllowListUris.ts
src/storage/getUnparsedAllowLists.ts
src/storage/storeAllowListData.ts
src/storage/storeAllowListRecords.ts
src/storage/storeAttestations.ts
src/storage/storeClaim.ts
src/storage/storeHypercertAllowList.ts
src/storage/storeMetadata.ts
src/storage/storeSupportedSchemas.ts
src/storage/storeTransferSingleFraction.ts
src/storage/storeUnits.ts
src/types/database-generated.types.ts
supabase/migrations/20240223130157_init_indexing_tables.sql
supabase/migrations/20240303225928_add_functions.sql

* Define parsed on hc_allowlist_data row
* Improved consistency in log types
* Simplified supabase error handling. Throwonerror() where possible
* tweaked queries and schemas

fix(allowlist): allowlist parsing, storage and general call logic

---

supabase/migrations/20240521095300_mint_claim_from_allowlist.sql

* Migration had new not null columns. This broke the migration because the DB already had records

fix(nullable): default values for allowlist records

---

src/indexer/indexClaimsStored.ts
src/parsing/claimStoredEvent.ts

Batchwise parsing claimStored logs to rate limit calls to RPC provide

feat(parse): batchwise parsing claimstored logs

---

src/storage/storeTransferSingleFraction.ts
src/storage/storeUnits.ts
src/types/database-generated.types.ts

defautlToNull to false to fix `[runIndexing] Failed to index events PostgrestError: null value in column "id" of relation "fractions" violates not-null constraint`

fix(id): defaultToNull to false for autogenerating ids

---

src/storage/storeTransferSingleFraction.ts
src/storage/storeUnits.ts
test/parsing/transferSingleEvent.test.ts
test/parsing/valueTransferEvent.test.ts
test/storage/storeTransferSingleFraction.test.ts

* Removes redundant logging of TRANSFER while logging unit transfer
* Matched token owners on lowercased addresses

fix: match addresses lowercased

---

src/fetching/fetchMetadataFromUri.ts
src/indexer/indexMetadata.ts
src/storage/storeMetadata.ts
src/utils/metadata.zod.ts

Replace the metadata schema validation because for storage purposes we want to store all metadata that matches our format, even when for instance timestamps don't make sense.
* Create single Zod schema for metadata validation that only validated on the correct types
* Remove duplicated validation steps
* Replaces `validateMetadata` from SDK with zod schema

fix(metadata): cleanup metadata validation

---

seed.ts
src/fetching/fetchMetadataFromUri.ts
src/indexer/indexAllowlistSingleClaimMinted.ts
src/parsing/leafClaimedEvent.ts
src/storage/updateAllowlistRecordClaimed.ts
src/types/database-generated.types.ts
src/types/types.ts
test/parsing/leafClaimedEvent.test.ts
test/resources/mockMetadata.ts

This PR fixes the allowlist indexing that broke on the updated column names. Some additional improvements were made for more robust processing.
* LeafClaimed as zod typed schema
* Fetch records on `creation_block_number` instead of `block_number`
* Update contract events and abort when no events were found
* Uses `claimable_fractions_with_proofs` view instead of old view

fix(allowlist): indexing allowlist records

---

src/storage/storeTransferSingle.ts
src/storage/storeValueTransfer.ts

Updates fraction and unit transfer methods to fetch tokens with claims_id, not only token ID. This to prevent access to tokens from a different chain/contracts.

fix(bug): get tokens with claimsID to prevent overlap between chains

---

package.json
pnpm-lock.yaml
src/fetching/fetchAllowlistFromUri.ts
src/indexer/LogParser.ts
src/indexer/chainsauce.ts
src/indexer/eventHandlers.ts
src/indexer/indexAllowlistData.ts
src/indexer/indexMetadata.ts
src/parsing/attestedEvent.ts
src/parsing/batchValueTransferEvent.ts
src/parsing/claimStoredEvent.ts
src/parsing/leafClaimedEvent.ts
src/parsing/metadata.ts
src/parsing/parseTakerBid.ts
src/parsing/transferBatchEvent.ts
src/parsing/transferSingleEvent.ts
src/parsing/valueTransferEvent.ts
src/storage/storeClaimStored.ts
src/storage/storeMetadata.ts
src/types/database-generated.types.ts
src/types/types.ts
src/utils/fetchFromHttpsOrIpfs.ts
src/utils/metadata.zod.ts

Uses updated chainsauce instance that adds a caching layer for data calls. The goal is to speed up re-indexing on bigger chains by reducing fetching traffic, especially since IPFS can be slower than regular https calls.
* Stores fetched data in public.data tables
* Add `getData` methods from chainsauce to give event handlers access to db data
* Updates `log` input for parser method to `data`
* Explicitly declare indexing of metadata, allowlist data and allowlist records at the env of the ClaimStored event handler

feat(cache): cache data calls in local db

---

package.json
pnpm-lock.yaml

Uses @hypercerts-org/chainsauce 1.0.24 with removes parameters from the index. Indexing on OP resulted in 1000s of `index row size 3968 exceeds btree version 4 maximum 2704 for index "idx_events"` errors. The index table used parameters, which is a json dump. This update removes the params column from the index.

fix(cache): chainsauce 1.0.24 with updated index declaration

---

.github/workflows/supabase-ci-staging.yml
.github/workflows/supabase-ci-test.yml
package.json
pnpm-lock.yaml
seed.ts
src/clients/evmClient.ts
src/utils/getDeployment.ts

* Updates hypercerts packages to version supporting arbitrum one
* Add running the seed script to the CI action for consistent DB rollout

feat(arbOne): update seed script with arb contracts and update gha

---

src/indexer/chainsauce.ts

To reduce hitting scaling limits in Alchemy, reduce polling rate on testnet from 1 to 5 seconds and on prod from 1 to 2.5 seconds

fix: 5s polling testnet, 2.5s polling prd

---

.env.template
.github/workflows/supabase-ci-production.yml
.github/workflows/supabase-ci-staging.yml
.github/workflows/supabase-ci-test.yml
README.md
package.json
pnpm-lock.yaml
seed.ts
src/clients/evmClient.ts
src/indexer/chainsauce.ts
src/indexer/indexer.ts
src/instrument.mjs
src/parsing/parseTakerBidEvent.ts
src/types/database-generated.types.ts
src/utils/getDeployment.ts
src/utils/metadata.zod.ts
supabase/migrations/20240830131559_enable_realtime_tables.sql

* Filecoin calibration support
* Lowered polling rates
* Updated readme and setup instructions
* Celo marketplace supports
* Updated dependencies (hypercerts packages)

Push to PRD

---

src/utils/getDeployment.ts

Adds the Celo EAS an Registry contract addresses to the `getDeployment` method, so that the validation of Attested events on Celo doesn't fail.

Add Celo EAS addresses to deployment getter

---

seed.ts
src/utils/getDeployment.ts

Adds the EAS and Schema Registry contract addresses for Celo as documented here: https://docs.attest.org/docs/quick--start/contracts

Push Celo EAS contract addresses

---

src/storage/storeMetadata.ts

When properties are attached to the metadata, first parse the object to make it suitable for storage

fix(storeMetadata): handling of properties field

---

src/parsing/parseTakerBidEvent.ts
test/parsing/takerBidEvent.test.ts
vitest.config.ts

Closes #242 
This PR updates the `parseTakerBidEvents` method to handle the two possible types of sales events. When the full fraction is sold, the marketplace simple executes a transfer (`TransferSingle`) instead of a split and transfer of values (`BatchValueTransfer`). 
Additionally, the test suite for this handler was added

Takerbid event parsing

---

src/clients/rpcClientFactory.ts

increasing the delay when retrying a request will fix throughput errors, where we are performing too many requests to infura per second.

fix: increase the retry delay in case a request fails

---

src/instrument.mjs

As we're getting high loads on Sentry spans, we reduce the sampling rate from 1.0 to 0.1 for production and 1.0 on staging.
The reason for this is to primarily lower the amount of traces sent. However, we keep it 100% on staging to detect bugs and as traffic is lower there
Closing #261

chore(sentry): lower sampling rates`
