package.json
pnpm-lock.yaml
rollup.config.mjs

* Rollup build with sentry deps

fix(build): build with rollup and sentry sourcemaps

---

.env.template
package.json
pnpm-lock.yaml

fix(env): add dotenv

---

src/storage/index.ts

fix(build): fix import errors

---

package.json
pnpm-lock.yaml
src/clients/evmClient.ts
src/server.ts
src/utils/getDeployment.ts
supabase/seed.sql

feat(base): enable base sepolia and update types

---

src/server.ts

* Restore hypercerts and schema indexing

fix(indexing): restore disabled methods

---

supabase/migrations/20240223130157_init_indexing_tables.sql
supabase/migrations/20240303225928_add_search_functions.sql

* Redeployed staging tables to enable totalCounts

fix(indexing): totalCount on staging tables

---

src/indexer/indexClaimsStored.ts
src/storage/storeTokens.ts

20 indexer index on chain token ownership state

---

src/fetching/fetchAllowlistFromUri.ts
src/parsing/attestedEvent.ts
src/parsing/claimStoredEvent.ts

fix(typos): ghost in the machine

---

package.json

https://nixpacks.com/docs/providers/node

fix(ci): hardcode pnpm version

---

src/fetching/fetchAttestationData.ts
src/indexer/indexAttestations.ts
src/parsing/attestationData.ts
src/parsing/attestedEvent.ts
src/server.ts
src/storage/storeAttestations.ts
src/storage/storeMetadata.ts
src/types/database-generated.types.ts
supabase/migrations/20240520093935_update_attestation_colum_names.sql

* Created migration for updated db columns
* Updated attestation handlers to use received objects
* Cleaned up some parsing logic
* Updated method annotations

fix(db): match eas column names and update handlers

---

src/indexer/indexAttestations.ts
src/parsing/attestationData.ts

* Improved handling of failed attestations decoding
* Updated filtering on null or undefined when decodedAttestation objects are returned
* Increased attestation indexing size

fix(parsing): parsing bigints in attestations

---

src/storage/storeAttestations.ts
src/storage/storeUnits.ts

* Solves `[IndexAttestations] Error while fetching and updating attestation data PostgrestError: duplicate key value violates unique constraint "attestations_supported_schemas_id_attestation_uid_key"` by allowing upserts

feat(attest): allow upserting records

---

src/indexer/indexSupportedSchemas.ts

* don't log error but debug and return silently

fix(log): log as debug instead of error

---

src/fetching/fetchAllowlistFromUri.ts
src/indexer/indexAllowlistRecords.ts
src/storage/getUnparsedAllowListsRecords.ts
src/storage/storeAllowListData.ts
src/storage/storeAllowListRecords.ts
src/storage/storeAttestations.ts
src/storage/storeHypercertAllowList.ts
src/storage/storeMetadata.ts
src/storage/storeSupportedSchemas.ts
src/storage/storeUnits.ts
src/utils/parseToOzMerkleTree.ts

fix(types): use db generated typed for store input

---

src/utils/tokenIds.ts
supabase/migrations/20240605092059_update_rls_policies.sql

* Removed redundant local var and logging in tokenId.ts util
* Updated RLS policies

fix(rls): apply correct RLS policies

---

src/indexer/indexClaimsStored.ts
src/monitoring/hypercerts.ts
src/parsing/claimStoredEvent.ts
test/parsing/claimStoredEvent.test.ts
vitest.config.ts

* Remove ownerOf call to reduce RPC load (it's always the zero-address)
* Remove reduntant logs

fix(calls): remove ownerOf call and update test

---

src/clients/evmClient.ts

* Add 1500ms delay between retries
* Rank fallback providers

fix(evm): retry delay and rank providers

---

src/indexer/indexFractionTransfers.ts
src/indexer/indexUnitTransfers.ts

* Batch token transfers
* Batch unit transfers

fix(batch): batch all transfer RPC calls

---

src/storage/storeMetadata.ts
test/storage/storeMetadata.test.ts

* Removes logical checks on timeframes in metadata zod schema applied before storing metadata
* Updated tests
Closes #105

fix(parse): no logical checks on metadata parsing

---

.github/workflows/ci-test-integration.yml
src/storage/storeMetadata.ts
src/utils/fetchFromHttpsOrIpfs.ts
src/utils/fetching.ts
test/storage/storeMetadata.test.ts

Reverts hypercerts-org/hypercerts-indexer#109

Revert "Replace errors with warns"

---

src/parsing/attestedEvent.ts

fix(msg): validation msgs

---

src/storage/storeMetadata.ts

fix(zod): recommit skipped logic

---

src/clients/evmClient.ts

* Add Base support
* Add Celo support

feat(chains): add base and celo

---

src/clients/evmClient.ts

feat(rpc): add rpc urls for celo, base

---

supabase/migrations/20240619085140_add_view_claimable_fractions_with_proofs.sql

Adds view for allowlist claim flows

feat(allowlist): view for claiming fractions

---

seed.ts
src/indexer/indexFractionTransfers.ts
src/indexer/indexUnitTransfers.ts
src/parsing/transferSingleEvent.ts
src/parsing/valueTransferEvent.ts
src/storage/storeTransferSingleFraction.ts
src/storage/storeUnits.ts
src/types/types.ts

* Improves seed script with all production chains
* Improves typed handling of transferSingle and valueTransfer events
*

fix(ids): generated ids for fractions

---

src/utils/getDeployment.ts

Add Base and Celo to getDeployments

chore(config): add supported chain deployments

---

package.json
pnpm-lock.yaml

Node runner to 20
removed unused deps

fix(railway): package deps and node version

---

.github/workflows/ci-test-integration.yml
integration/indexClaimStoredEvents.test.ts
integration/indexFractionTransfer.test.ts
integration/indexUnitsAndFractionTransferedEvents.test.ts
integration/indexUnitsTransferedEvents.test.ts
integration/setup-env.ts
seed.ts
src/indexer/indexAllowlistSingleClaimMinted.ts
src/indexer/indexBatchFractionTransfers.ts
src/indexer/indexBatchValueTransfer.ts
src/indexer/indexClaimsStored.ts
src/indexer/indexFractionTransfers.ts
src/indexer/indexTakerBid.ts
src/indexer/indexValueTransfer.ts
src/monitoring/hypercerts.ts
src/storage/storeFractionTransfer.ts
src/storage/storeUnits.ts
src/utils/getBlocksToFetch.ts
src/utils/getMostRecentOrDefined.ts
test/handlers.ts
test/helpers/transactions.ts
test/storage/storeTransferSingleFraction.test.ts
test/utils/getBlocksToFetch.test.ts

This PR aims to fix the test suites, and some minor issues found while building the tests, as to have a reproducable environment for testing errors and issues. This leads up to quashing the open issues with fraction and allowlist claim indexing
* Fixes all units tests
* Updates and fixes 5/6 unit tests
* Fixes the seed script so it provides the supported schemas
* Updates in indexing logic for throws and last_block_index updating

Indexer tests and stability

---

seed.ts
src/indexer/eventHandlers.ts
src/indexer/processLogs.ts
src/indexer/runIndexing.ts
src/parsing/attestationData.ts
src/parsing/attestedEvent.ts
src/parsing/batchValueTransferEvent.ts
src/parsing/claimStoredEvent.ts
src/parsing/leafClaimedEvent.ts
src/parsing/parseTakerBid.ts
src/parsing/transferBatchEvent.ts
src/parsing/transferSingleEvent.ts
src/parsing/valueTransferEvent.ts
src/storage/getContractEventsForChain.ts
src/storage/getSupportedSchemas.ts
src/storage/getUnparsedAllowListsRecords.ts
src/storage/storeAttestations.ts
src/storage/updateAllowlistRecordClaimed.ts
src/utils/metadata.zod.ts
test/parsing/claimStoredEvent.test.ts

* Removes unused 'AllowlistCreated' event
* Typed eventhandlers
* Add context to parsed methods
* Cleanup `runIndexing` method
* Add block to context to reduce RPC calls and speed-up indexing
* More optional fields in metadata parsing

chore(cleanup): types, handlers, logging

---

package.json
pnpm-lock.yaml
src/fetching/fetchMetadataFromUri.ts
src/indexer/chainsauce.ts
src/parsing/valueTransferEvent.ts
src/storage/storeValueTransfer.ts
src/types/database-generated.types.ts
src/utils/constants.ts
src/utils/fetchFromHttpsOrIpfs.ts
src/utils/fetching.ts

This PR fixes the caching layer of the event indexing process by implementing our fork of [chainsauce](https://github.com/hypercerts-org/chainsauce/).
Event, block, transaction calls will be stored in a local postgres instance to speed up indexing.

chainsauce indexing

---

src/parsing/metadata.ts
src/storage/storeMetadata.ts

* Removes dataToStore log line
* Cleans up unused imports

fix(log): remove redundant logging

---

package.json
pnpm-lock.yaml
seed.ts
src/utils/getDeployment.ts

* Updates marketplace, hypercerts SDKs and contracts packages 
* Uses updated depoyments export

chore(bump): update packages and constants import

---

src/indexer/requestQueue.ts
src/parsing/parseUriEvent.ts
src/storage/storeClaimStored.ts

* Batch storage of tx per event requests
* Add `uri` to claim on upsert

fix(uri): add uri on claim stored upsert

---

package.json
pnpm-lock.yaml
seed.ts

chore(update): update contracts, sdk and marketplace package

---

package.json
pnpm-lock.yaml
seed.ts

* Add OP HypercertsExchange to seed script
* Update hypercerts packages

chore(update): update packages and seed script

---

package.json
pnpm-lock.yaml
seed.ts
src/clients/evmClient.ts

Updates RPCs, supported chains and the hypercerts packages

Release Arb testnet indexing support

---

.github/workflows/supabase-ci-production.yml
.github/workflows/supabase-ci-test.yml
package.json
pnpm-lock.yaml
supabase/migrations/20240830131559_enable_realtime_tables.sql

Updates supabase to latest version

chore(update): supabase npm package

---

src/parsing/parseTakerBidEvent.ts

fix(sales): get correct address for buyer and seller

---

seed.ts

Basic evaluation schema on:
- Arb
- Base
- Optimism
- Base Sepolia

feat(eas): basic evaluation on all chains

---

.env.template
README.md
src/instrument.mjs

* Cleanup env.template
* Init README
* Overview diagram
* Updates Sentry initialization to be disabled when runnign locally

Outline setup and architecture

---

src/parsing/parseTakerBidEvent.ts

fix(import): missing js extension in import

---

seed.ts

Adds support for creator updates. The attestation documents files uploaded on IPFS or links and allow for adding additional data to an impact claim.

Add schema for creator updates (Sepolia)

---

seed.ts

Add support for Arb, OP, Base, Celo, Base Sepolia

Add EAS creator feed schemas for all supported chains
